language: python
python:
    - "3.4"
    - "3.5"
install:
    - pip install -r requirements/development.txt
script:
    - python wpsblog/manage.py test users posts bitly wpsblog
notifications:
    slack: pn101:FSNKDNyG3u0ckfwHrEHvk5pG
    email: false
