# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wpsblog', '0002_naverpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverpost',
            name='keyword',
            field=models.CharField(default='No record', max_length=16),
            preserve_default=False,
        ),
    ]
